"""
This module is auto generated by azure-ml-component.

Assets included:
    - file:../../../../local_components/mpi/component.yaml
    - file:../../../../local_components/copy_files/component.yaml
    - file:../../../../local_components/hdi-component/component_spec.yaml
    - file:../../../../local_components/scope_component/toss/component_spec.yaml
    - file:../../../../local_components/sweep_component/sweep.spec.yaml
"""
# THIS IS AN AUTO GENERATED FILE.
# PLEASE DO NOT MODIFY MANUALLY.
from ._assets import (
    microsoft_com_azureml_samples_hello_world_with_cpu_image,
    microsoft_com_azureml_samples_parallel_copy_files_v1,
    microsoft_com_azureml_samples_train_in_spark,
    bing_relevance_convert2ss,
    microsoft_com_azureml_samples_tune,
)

_assets_spec = [
    'file:../../../../local_components/mpi/component.yaml',
    'file:../../../../local_components/copy_files/component.yaml',
    'file:../../../../local_components/hdi-component/component_spec.yaml',
    'file:../../../../local_components/scope_component/toss/component_spec.yaml',
    'file:../../../../local_components/sweep_component/sweep.spec.yaml',
]

__all__ = [
    'microsoft_com_azureml_samples_hello_world_with_cpu_image',
    'microsoft_com_azureml_samples_parallel_copy_files_v1',
    'microsoft_com_azureml_samples_train_in_spark',
    'bing_relevance_convert2ss',
    'microsoft_com_azureml_samples_tune',
]