channels:
- defaults
dependencies:
- python=3.6.10
- pip:
  - --extra-index-url=https://azuremlsdktestpypi.azureedge.net/CLI-SDK-Runners-Validation/17787158
  - azureml-defaults==0.1.0.17787158
  - azureml-pipeline-wrapper==0.1.0.17787158
name: project_environment
